### ISSUE TITLE
Get current AC State

### ISSUE THREAD

**Issue by natanrolnik** [thetonto/node-red-contrib-sensibo#18]
Hey @thetonto , thank you so much for creating this package.

I've noticed that there's no way of currently fetching the current (or last) `acState`, right?

How hard would it be to add a new node type called _AC State_, which gets a given pod's last state? To do so, the endpoint should be `pods/<pod-id>/acStates?limit=1`.

I could try doing so, although I have no idea how to debug it.

**Comment by thetonto** [comment]
I currently have the dev environment open and working so will have a look at how to add this to the system.  Instead of adding another node the function could be added to the Sensibo-In node with the option to retrieve the current AC State.

**Comment by natanrolnik** [comment]
That would be great, @thetonto !

**Comment by thetonto** [comment]
Hi @natanrolnik 
New version about to be released which has the option to just get the AC State.  Also included now is an example flow of how teh nodes can be used.

**Comment by natanrolnik** [comment]
Amazing, well done @thetonto 👏🏻
