### ISSUE TITLE
Payload injection to send

### ISSUE THREAD

**Issue by petez69** [thetonto/node-red-contrib-sensibo#4]
Hi there.  Maybe its a little too late at night but I'm trying to simply send msg.on with a boolean payload of true to sendibo-send.

I'm using an injection node and then a change node to convert from msg.topic to msg.on

Its sending to sensibo however the message format must be wrong, hear the beep and get debug to say the message was successfully received.

Any help would be appreciated (example would be great)

Thankyou..Peter

**Comment by thetonto** [comment]
Hi Peter.
I've just checked this on my home unit along the same line.  Inject node.
The change node is however a string.  Not a boolean.  That could be the issue.  I have tested it now as boolean and unit turned off.    Version is 0.3.3

**Comment by petez69** [comment]
Hi there

Thanks for the reply...

I ended up using a change node to inject the correct message....basically Set msg.on to true (string).  I think when I did it with Boolean it didn't work...definitely works now :-) THANKYOU

One thing too with the polling of the aircon status,  I'm stripping out values every 2 mins using timestamp as the timer.  I note the polling node seems to continue to poll itself even though the config box is still checked and I see errors in the debug.  

Stuff like:
Function : (error)
"TypeError: Cannot read property 'measurements' of undefined"

msg : error
"StatusCodeError: 404 - {"status":"failed","reason":"NotFound","message":"No such device or device is not associated with user"}"

Not sure why I'm seeing this, made setting it up a little difficult as I wasn't sure if I was generating the error or not....

I can post the flow, its VERY simple.....

**Comment by thetonto** [comment]
Great to hear it is working.  If you can post the flow that would be great.

**Comment by petez69** [comment]
[{"id":"c27928f5.f9b598","type":"sensibo in","z":"34cecf31.8e475","sensiboAPI":"25996135.b37d9e","name":"Shed Airconditioner","pod":"123456","getconfig":true,"polltime":"0","x":530,"y":240,"wires":[["e5f480f3.aa454","39e61698.40b04a"]]},{"id":"5e45faea.f09ca4","type":"inject","z":"34cecf31.8e475","name":"","topic":"","payload":"","payloadType":"date","repeat":"120","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":240,"wires":[["c27928f5.f9b598","6e07452c.6669fc","d974ffc1.07b1"]]},{"id":"e5f480f3.aa454","type":"function","z":"34cecf31.8e475","name":"Extract Temperature","func":"var airtemp = msg.result.measurements.temperature;\nvar msg = {\n\npayload:airtemp\n\n};\n\nreturn msg;\n","outputs":1,"noerr":0,"x":780,"y":240,"wires":[["97afe458.a5d758"]]},{"id":"97afe458.a5d758","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Temp","topic":"stat/Sensibo/shed/temperature","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1020,"y":240,"wires":[]},{"id":"39e61698.40b04a","type":"function","z":"34cecf31.8e475","name":"Extract Humidity","func":"var humidity = msg.result.measurements.humidity;\nvar msg = {\n\npayload:humidity\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":760,"y":300,"wires":[["c20b16d8.c35b58"]]},{"id":"c20b16d8.c35b58","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Humidity","topic":"stat/Sensibo/shed/humidity","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1010,"y":300,"wires":[]},{"id":"6e07452c.6669fc","type":"sensibo in","z":"34cecf31.8e475","sensiboAPI":"25996135.b37d9e","name":"Lounge Airconditioner","pod":"123456","getconfig":true,"polltime":"0","x":540,"y":360,"wires":[["1c211d61.3e0ff3","eb627532.9cc658"]]},{"id":"1c211d61.3e0ff3","type":"function","z":"34cecf31.8e475","name":"Extract Temperature","func":"var airtemp = msg.result.measurements.temperature;\nvar msg = {\n\npayload:airtemp\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":780,"y":360,"wires":[["11d63ed.bbc2dc1"]]},{"id":"eb627532.9cc658","type":"function","z":"34cecf31.8e475","name":"Extract Humidity","func":"var humidity = msg.result.measurements.humidity;\nvar msg = {\n\npayload:humidity\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":760,"y":420,"wires":[["381913a5.94c76c"]]},{"id":"11d63ed.bbc2dc1","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Temp","topic":"stat/Sensibo/loungeroom/temperature","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1000,"y":360,"wires":[]},{"id":"381913a5.94c76c","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Humidity","topic":"stat/Sensibo/loungeroom/humidity","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1010,"y":420,"wires":[]},{"id":"d974ffc1.07b1","type":"sensibo in","z":"34cecf31.8e475","sensiboAPI":"25996135.b37d9e","name":"Bedroom Airconditioner","pod":"123456","getconfig":true,"polltime":"0","x":550,"y":500,"wires":[["583a5973.5750c8","38c2fb73.df77e4"]]},{"id":"583a5973.5750c8","type":"function","z":"34cecf31.8e475","name":"Extract Temperature","func":"var airtemp = msg.result.measurements.temperature;\nvar msg = {\n\npayload:airtemp\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":780,"y":500,"wires":[["e4f5c908.35c128"]]},{"id":"38c2fb73.df77e4","type":"function","z":"34cecf31.8e475","name":"Extract Humidity","func":"var humidity = msg.result.measurements.humidity;\nvar msg = {\n\npayload:humidity\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":760,"y":560,"wires":[["57bbb517.c216dc"]]},{"id":"e4f5c908.35c128","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Temp","topic":"stat/Sensibo/bedroom/temperature","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1000,"y":500,"wires":[]},{"id":"57bbb517.c216dc","type":"mqtt out","z":"34cecf31.8e475","name":"Publish Humidity","topic":"stat/Sensibo/bedroom/humidity","qos":"","retain":"","broker":"f5d8a9f9.f51988","x":1010,"y":560,"wires":[]},{"id":"25996135.b37d9e","type":"sensibo-config","z":"","senAPI":"123456"},{"id":"f5d8a9f9.f51988","type":"mqtt-broker","z":"","name":"","broker":"mqtt.local","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]
