### ISSUE TITLE
PRs accepted?

### ISSUE THREAD

**Issue by Roaders** [thetonto/node-red-contrib-sensibo#8]
Hi

If I did some work on this node would you accept and release pull requests.
What I plan:
- to move acState properties to msg.payload rather than just msg to make it fit better with other nodes
- to list names of pods to select from rather than having to type in the id

I couldn't actually get this node to work at all so I'd look at why it didn't work for me as well. I am currently just using a http request node instead

**Comment by thetonto** [comment]
Hi Roaders
Always happy to have others contribute to this project.   Firstly thou I am curious as to why the node did not work.  After entering the API key from Sensibo the node should then call up the various to list.  There should be no need to enter the ID manually.  I am checking that I am running the latest published version as it is now winter here in OZ and I've been using the node I had installed as part of my end of day to turn on the Aircon with no issues.

Lets focus on getting the node running correctly and then we can work on the move of acStates to the msg.payload as will want to make sure it does not break current users

Update which may not be in the help.  Is after you enter the API key you need to click on the looking glass icon and it will present a drop down list and then it will show you the nodes you have available to select.

The drop down list from clicking the looking glass icon will show the normal name of each node, but store the actual name.  I spent days trying to always show the normal name but never found a good way to do this.  At the end of it I thought the compromise of showing the friendly name but storing the actual name was a suitable compromise as once the config node is setup you don't need to go back to it and the main function is in the actual working nodes.  Any assistance on fixing this is appreciated.

**Comment by thetonto** [comment]
Checking the working nodes with regards to acState properties.  In the node that sends commends it is embedded into the full return message which also contains the status 
payload.status
payload.result.acState

both of which you will want on the return message.

With regards to the Sensibo In node I think you are correct as it returns nothing in the payload.  Bit of an oversight there.  I think this can be updated to send to poth parts of the message so won't break any current users.
